### ISSUE TITLE
Cannot access this repository

### ISSUE THREAD

**Issue by RAFAY-AAMIR-GULL** [NVlabs/handover-sim#1]
Hi,
I hope you are doing good.

I am trying to clone this repository (handoversim) into my local machine using the procedure mentioned in the README of this repo with this command (git clone --recursive git@github.com:NVlabs/handover-sim.git). The problem that my machine raise is :
""
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
""

Can you please fix it as soon as possible?

**Comment by ychao-nvidia** [comment]
This is an issue of your GitHub config and not the repo itself.

To fix it, you can either:

1. [add your SSH key to your GitHub account](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account), or

2. [clone the repo using HTTPS](https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository):

    ```
    git clone --recursive https://github.com/NVlabs/handover-sim.git
    ```
