### ISSUE TITLE
Request for Training Code for Human-Robot Handovers in handover-sim Environment

### ISSUE THREAD

**Issue by HWPengSYSU1993** [NVlabs/handover-sim#10]
I am impressed by the capabilities and features of the handover-sim environment.

I kindly request your assistance in accessing the training code for human-robot handovers in the handover-sim environment. If it is possible, I would greatly appreciate it if you could share the code with me or provide any guidance on how I can access it. Any additional documentation, instructions, or insights you can provide would be immensely helpful.

**Comment by HWPengSYSU1993** [comment]
Thank you for your response. I appreciate your great efforts in preparing the training code for the CVPR'23 paper. I will eagerly await the release of the code and any updates you provide. 

Thank you again for your assistance!

**Comment by ychao-nvidia** [comment]
We have released the code of our CVPR'23 paper [here](https://github.com/NVlabs/handover-sim2real).
