### ISSUE TITLE
FPS problem

### ISSUE THREAD

**Issue by yangyichu** [NVlabs/handover-sim#14]
Hi, I'm wondering why is _TIME_STEP_RAW in dex_ycb set to 0.04, in the paper, it says the dataset was collected at 30 fps.

**Comment by ychao-nvidia** [comment]
Yes, for DexYCB we streamed each camera at 30 fps. However, the final frame would drop a bit after synchronizing the 8 camera streams. We did not measure the final frame rate, and just ballparked it to be 25 fps (0.04 second per time step) here.
