### ISSUE TITLE
About Hand and Object Segmentation

### ISSUE THREAD

**Issue by aikuide** [NVlabs/handover-sim#17]
Hi！
In the paper, it is mentioned that the perception module obtained RGBD images and segmented images to obtain segmented point clouds of objects and hands. I would like to know how to obtain segmented images?

**Comment by ychao-nvidia** [comment]
If you are referring to the simulation experiments, the segmentation images are directly rendered from the simulation engine (Bullet).

**Comment by aikuide** [comment]
Sorry, I may not be familiar with what you are talking about rendering. It requires neural network training on the dataset of hands and objects to achieve the segmentation target code

**Comment by aikuide** [comment]
Sorry, I may not be familiar with what you mean by rendering. Does it require neural network training on the dataset of hands and objects to achieve segmentation

**Comment by ychao-nvidia** [comment]
IIRC Bullet uses an OpenGL based renderer. This is classical rendering and does not require neural network.

**Comment by aikuide** [comment]
![微信截图_20240520104028](https://github.com/NVlabs/handover-sim/assets/118355475/8db31984-4744-4593-b728-dcde283c7947)
Thank you very much for your patient answer. So how can I obtain such segmented images in the paper

**Comment by ychao-nvidia** [comment]
The segmented image is obtained in [this line](https://github.com/NVlabs/handover-sim/blob/f585c0d2dde897048ff5ca1bb4c29a0192aa28db/handover/panda.py#L126). You should be able to check it if you run the demo.

**Comment by aikuide** [comment]
So what do you mean is that you can directly obtain such segmented images through rendering and then pass them directly to the perception module? In my understanding, real-time segmentation of hands and objects is also a difficult task

**Comment by ychao-nvidia** [comment]
> You can directly obtain such segmented images through rendering and then pass them directly to the perception module?

Yes.

> Real-time segmentation of hands and objects is also a difficult task.

It does not matter in simulation. In the real world, yes.

**Comment by aikuide** [comment]
Thank you for your patient answer
