### ISSUE TITLE
TypeError:__init__() got an unexpected keyword argument 'betas'

### ISSUE THREAD

**Issue by xcyxpz** [NVlabs/handover-sim#2]
Hi!

I had this problem when I was compiling  'compile_mano_assets.py'. I cannot figure out why. The error is as below.

Compiling MANO assets
Traceback (most recent call last):
  File "compile_mano_assets.py", line 391, in <module>
    main()
  File "compile_mano_assets.py", line 157, in main
    model = HandModel45(
TypeError: __init__() got an unexpected keyword argument 'betas'

Looking forward to your reply.

**Comment by ychao-nvidia** [comment]
Somehow your mano_pybullet submodule is not on the [right commit](https://github.com/ychao-nvidia/mano_pybullet/commits/ac6fd6f8c01d103c52e63bb0d1d89265891738e8). You can fix it by:

1. Checkout the right commit:

    ```
    cd mano_pybullet
    git checkout ac6fd6f
    cd ..
    ```

2. Make sure your mano_pybullet is installed from the submodule. Run `pip freeze | grep mano_pybullet`. You should see:

    ```
    -e git+ssh://git@github.com/ychao-nvidia/mano_pybullet.git@ac6fd6f8c01d103c52e63bb0d1d89265891738e8#egg=mano_pybullet&subdirectory=../../mano_pybullet
    ```

    If not, run the following:

    ```
    pip install --no-deps -e mano_pybullet
    ```

**Comment by xcyxpz** [comment]
Oh, I didn't notice the commit. Anyway, it has now been successfully reproduced. Thanks!
