### ISSUE TITLE
pybullet installation

### ISSUE THREAD

**Issue by joannanananana** [NVlabs/handover-sim#3]
Hi,
I encountered a problem when installing packages according to your process.
Do you have any idea about this problem.

Thanks

<img width="622" alt="屏幕截图_20221209_040859" src="https://user-images.githubusercontent.com/93474691/206655528-48e23c76-ed13-46b3-b3f6-0d3081f2b86c.png">

**Comment by joannanananana** [comment]
or could you please provide an environment package version? 
When installing by "pip install -e .   " , some package installation fails.

**Comment by ychao-nvidia** [comment]
Looks like you need a newer version of Microsoft Visual C++ (>=14.0). You may want to retry after installing the required version. Also note that this repo has so far been tested on Linux not been tested on Linux, but not on Windows.

**Comment by joannanananana** [comment]
After trying on ubuntu20.04, it works.
Thanks for you suggest and great work.
