### ISSUE TITLE
The problem of robot in simulation

### ISSUE THREAD

**Issue by barrycxg** [NVlabs/handover-sim#5]
It is a great job. I want to change robot type in simulation. Does the code provide an interface to change the urdf file of the robot?

**Comment by ychao-nvidia** [comment]
Yes. The robot body is currently specified in `HandoverEnv` [here](https://github.com/NVlabs/handover-sim/blob/7dfeea3f5e24d4177421c3e4011261f2f066e313/handover/handover_env.py#L21) and [here](https://github.com/NVlabs/handover-sim/blob/5c75eba3cbd6f7f9e18113e56bc667705840c08e/handover/handover_env.py#L327), which calls the `Panda` class defined [here](https://github.com/NVlabs/handover-sim/blob/af0d4f70f502b8ed99e8323e3aae76da5c720a1e/handover/panda.py#L22). To change the robot, you need to create another class like `Panda` and change the robot attributes defined [here](https://github.com/NVlabs/handover-sim/blob/af0d4f70f502b8ed99e8323e3aae76da5c720a1e/handover/panda.py#L36-L52) (including the URDF file). Note that this interface to the simulator is using a library called [easysim](https://github.com/NVlabs/easysim).

**Comment by barrycxg** [comment]
Thanks for your reply. 
But I have an another question. How to define root joint in your code? Which joint is related to the wrist in the variable "root trans" ?

Sorry to disturb you again and thanks for your kindness!

**Comment by ychao-nvidia** [comment]
> How to define root joint in your code?

The kinematics of robot is all defined based on its URDF file.

> Which joint is related to the wrist in the variable "root trans" ?

Assuming you are referring to the MANO hand, if you look at a MANO URDF file, the wrist joint should be `joint7`:

```
  <joint name="joint7" type="fixed">
   ...
  </joint>
```

`root_trans` [here](https://github.com/NVlabs/handover-sim/blob/a0e587c419012585cf82f05fd66ade706b53a0a7/handover/dex_ycb.py#L152) is a constant translation from the base of URDF to the wrist joint.

**Comment by barrycxg** [comment]
Thanks for your reply and patience.  It helped me a lot.

**Comment by barrycxg** [comment]
I‘m sorry to disturb you. I‘m still confused that how to define the root joint in MANO hand. Is the root joint the wrist in your simulation？ If not, where is the root joint of MANO Hand defined in the code?

Thanks for your patience!

**Comment by ychao-nvidia** [comment]
> Is the root joint the wrist in your simulation?

No, the root joint is not the wrist. The root joint is a joint that has a constant translation (`root_trans`) from the wrist. This is an artifact from the MANO model.

> If not, where is the root joint of MANO Hand defined in the code?

Again, the kinematics is defined in the URDF, not in the Python code. To generate the URDF for MANO, you need to follow the [Installation](https://github.com/NVlabs/handover-sim#installation) section until step 5 to compile MANO assets (see [this](https://github.com/NVlabs/handover-sim/blob/master/handover/data/compile_assets.sh) and [this](https://github.com/NVlabs/handover-sim/blob/master/handover/data/compile_mano_assets.py)). The compilation leverages a submodule called [mano_pybullet](https://github.com/ychao-nvidia/mano_pybullet/tree/ac6fd6f8c01d103c52e63bb0d1d89265891738e8).

**Comment by barrycxg** [comment]
These do help! Thanks for your reply and patience.
