### ISSUE TITLE
b3Printf: URDF file '/home/user/handover-sim/handover/data/assets/table/table.urdf' not found

### ISSUE THREAD

**Issue by HWPengSYSU1993** [NVlabs/handover-sim#9]
Hi, thank you for your great work for human-to-robot handovers.

When I run a handover environment (Ubuntu20.04 python 3.8):
python examples/demo_handover_env.py \
  SIM.RENDER True

I meet the following error:

pybullet build time: May 20 2022 19:44:17
argv[0]=
startThreads creating 1 threads.
starting thread 0
started thread 0 
argc=3
argv[0] = --unused
argv[1] = 
argv[2] = --start_demo_name=Physics Server
ExampleBrowserThreadFunc started
X11 functions dynamically loaded using dlopen/dlsym OK!
X11 functions dynamically loaded using dlopen/dlsym OK!
Creating context
Created GL 3.3 context
Direct GLX rendering context obtained
Making context current
GL_VENDOR=NVIDIA Corporation
GL_RENDERER=NVIDIA GeForce RTX 4080/PCIe/SSE2
GL_VERSION=3.3.0 NVIDIA 525.105.17
GL_SHADING_LANGUAGE_VERSION=3.30 NVIDIA via Cg compiler
pthread_getconcurrency()=0
Version = 3.3.0 NVIDIA 525.105.17
Vendor = NVIDIA Corporation
Renderer = NVIDIA GeForce RTX 4080/PCIe/SSE2
b3Printf: Selected demo: Physics Server
startThreads creating 1 threads.
starting thread 0
started thread 0 
MotionThreadFunc thread started
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,152]:

b3Printf: URDF file '/home/hwpeng/handover-sim/handover/data/assets/table/table.urdf' not found

Traceback (most recent call last):
  File "examples/demo_handover_env.py", line 27, in <module>
    main()
  File "examples/demo_handover_env.py", line 19, in main
    env.reset(scene_id=scene_id)
  File "/home/user/.conda/envs/handover_sim/lib/python3.8/site-packages/gym/wrappers/order_enforcing.py", line 18, in reset
    return self.env.reset(**kwargs)
  File "/home/user/.conda/envs/handover_sim/lib/python3.8/site-packages/easysim/simulator_env.py", line 48, in reset
    self._simulator.reset(env_ids)
  File "/home/user/.conda/envs/handover_sim/lib/python3.8/site-packages/easysim/simulators/bullet.py", line 98, in reset
    self._load_body(body)
  File "/home/user/.conda/envs/handover_sim/lib/python3.8/site-packages/easysim/simulators/bullet.py", line 178, in _load_body
    self._body_ids[body.name] = self._p.loadURDF(body.urdf_file, **kwargs)
pybullet.error: Cannot load URDF file.
ven = NVIDIA Corporation
numActiveThreads = 0
stopping threads
Thread with taskId 0 exiting
Thread TERMINATED
destroy semaphore
semaphore destroyed
destroy main semaphore
main semaphore destroyed
finished
numActiveThreads = 0
btShutDownExampleBrowser stopping threads
Thread with taskId 0 exiting
Thread TERMINATED
destroy semaphore
semaphore destroyed
destroy main semaphore
main semaphore destroyed

**Comment by RAFAYAAMIR** [comment]
Hi @HWPengSYSU1993 

Can you please share? how did you resolve this issue, if it has been resolved?

**Comment by HWPengSYSU1993** [comment]
Hi @RAFAYAAMIR. Actually, I didn't follow the step-4 of "Download the DexYCB dataset". So I close this issue, as it work by following the instruction of installing the dataset.

**Comment by ychao-nvidia** [comment]
`handover-sim/handover/data/assets/table/table.urdf` should be generated in [Installation](https://github.com/NVlabs/handover-sim#installation) step 5. ii. (see [here](https://github.com/NVlabs/handover-sim/blob/f866bfccc2685f0114e13da7d19561a51779ea09/handover/data/compile_assets.sh#L6) and [here](https://github.com/NVlabs/handover-sim/blob/f3903379094d15a6f6a03dc6d2cd02d917132276/handover/data/compile_table_assets.py)). Make sure `pybullet` has been installed from step 2., and you have run step 5. i. to download and extract the assets.
